# Generated by Django 4.1 on 2022-11-03 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_post_commentpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['create'], 'verbose_name': 'maqola_menu', 'verbose_name_plural': 'maqolalar_menu'},
        ),
        migrations.AddField(
            model_name='menu',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='moder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
